import process from 'node:process';
import commonjs from '@rollup/plugin-commonjs';
import terser from '@rollup/plugin-terser';
import typescript from '@rollup/plugin-typescript';
import postcssImport from 'postcss-import';
import postcssPresetEnv from 'postcss-preset-env';
import copy from 'rollup-plugin-copy';
import postcss from 'rollup-plugin-postcss';

const TEST_VAULT_PLUGIN_DIR
	= 'obsidian-fountain-editor-test/.obsidian/plugins/fountain-editor';
const BUILD_DIR = 'build';

/* ------------------------------------ - ----------------------------------- */

const isProduction = process.env.BUILD === 'production';
const OUT_DIR = isProduction ? BUILD_DIR : TEST_VAULT_PLUGIN_DIR;

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ROLLUP
if you want to view the source, visit the plugin's github repository
*/
`;

const jsConfig = {
	input: 'src/main.ts',
	external: ['obsidian', '@codemirror/view', '@codemirror/state'],
	output: {
		dir: OUT_DIR,
		format: 'cjs',
		sourcemapExcludeSources: isProduction,
		exports: 'default',
		sourcemap: isProduction ? false : 'inline',
		banner: isProduction ? banner : undefined,
	},
	plugins: [
		typescript({
			sourceMap: !isProduction,
			inlineSourceMap: false,
			outDir: OUT_DIR,
			inlineSources: !isProduction,
			rootDir: './src',
		}),
		commonjs(),
		isProduction ? terser({format: {comments: false}}) : undefined,
		copy({
			targets: [{src: 'manifest.json', dest: OUT_DIR}],
			hook: 'writeBundle',
			// Verbose: true,
			overwrite: true,
		}),
	],
};

const cssConfig = {
	input: 'src/styles/index.css',
	output: {file: OUT_DIR + '/styles.css'},
	plugins: [
		postcss({
			extract: true,
			minimize: isProduction,
			sourceMap: !isProduction,
			plugins: [postcssImport(), postcssPresetEnv()],
		}),
	],
};

const config = [cssConfig, jsConfig];
export default config;
