blank_issues_enabled: false
contact_links:
  - name: 📄 Official Documentation
    url: https://obsidian-fountain-editor.chuangcaleb.com
    about: Check the official docs before creating a new ticket!
